### PR TITLE
Fixes to make it working with latest swiften

### PR DESCRIPTION
**Pull request by Ri0n**
Hi there!
This most likely is not intended for direct merge. But with all these changes/fixes I was able to compile with the latest Swiften and  make debs.
Use this pull request whatever way you want :-)

About disabled packages
mysql - won't find some header on Ubuntu 16.04.
pisggres - fails to link on Ubuntu 16.04.
libcommuni - just was too lazy to build it.

Have a nice day!

### CODE REVIEW

**Comment by vitalyster** [comment]
Can anyone run `make test` with this patch? Tests failed for me

**Comment by Fank** [comment]
Log from Dockerbuild: https://pastebin.com/81QiTBBp

**Comment by Ri0n** [comment]
yep, it's not backward compatible.

`NetworkPluginServer.cpp:310:17: error: 'fromString' is not a member of 'Swift::HostAddress'`

**Comment by vitalyster** [comment]
@Fank you have swiften3, while this patch requires swiften4

**Comment by Fank** [comment]
@Ri0n you need to updat the Dockerfile too.

**Comment by vitalyster** [comment]
@Ri0n I've failed tests with swiften4

**Comment by vitalyster** [comment]
found the problem - boost::asio::ip::address::from_string does not accept hostnames(localhost in test cases), replaced with 127.0.0.1. Also I have made compatibility macro for HostAddress. Fixed in https://github.com/hanzz/spectrum2/commit/6b45e0e418eef8c07e3c9499fba841ecb9df99e1

**Pull request closed without merging**
