### PR TITLE
Fixed travis build

### PR DESCRIPTION
**Pull request by Fank**

### CODE REVIEW

**Comment by vitalyster** [comment]
Tried this already, it doesn't enable xenial, just fall back to precise

**Comment by Fank** [comment]
ill try, it there must be a way .. :D

**Comment by vitalyster** [comment]
No, according to https://github.com/travis-ci/travis-ci/issues/5821 it isn't possible, but we can spin up Docker and run tests there

**Comment by Fank** [comment]
FFS :-1:

**Comment by vitalyster** [comment]
Last try was good. We just need to put communi package for xenial

**Comment by Fank** [comment]
If found a similar issue fix here https://github.com/ros2/ros2_embedded_riot/blob/master/.travis.yml

**Comment by vitalyster** [comment]
https://travis-ci.org/hanzz/spectrum2/builds/241808001 - finally fixed!

**Comment by Fank** [comment]
@vitalyster WOP WOP :ship:

**Pull request closed without merging**
