### PR TITLE
Switch from boost shared pointers to stl shared pointers

### PR DESCRIPTION
**Pull request by vladamatena**
As Swift switched shared pointer implementation from Boost to STL it is not possible to compile spectrum against latest (git version) Swift. This pull request fixes the problem by replacing boost shared pointer usages by STL counterparts in Spectrum code-base.

I do not insist on this change-set being merged. I just devoted my time to fix the compilation as I needed spectrum running on my server and I think it makes sense to reuse the fixes.

### CODE REVIEW

**Comment by vitalyster** [comment]
spectrum is able to use both swiften 2.0 (still present in LTS linux distributions) and 3.0 with version check macro HAVE_SWIFTEN_3. Swiften with std threads will be released as version 4, can you please add new macro (HAVE_SWIFTEN_4?) and use boost and std threads conditionally?

**Comment by vladamatena** [comment]
Sure, I can define macro for shared pointer namespace. I will let you know once I manage to get Swift 2,3,4 compatibility.

**Comment by vitalyster** [comment]
:+1:

**Comment by vladamatena** [comment]
I did the following changes to be able to compile against Swift 4:
- declared required compiler feature nullptr to force C++11 compilation mode (this may not be necessary, but compilation failed for me because of this)
- replaced all boost shared pointer usages with stl counterparts
- replaced few instances of boost::signals with boost::signals2
- remove include of swift/bsignals.h as it is not provided by Swift 4

I did following in order to be build against Swift 2,3:
- added include file include/Swiften/SwiftenCompat.h which defines macros for Swiften compatible namespaces for shared pointers and signals (a comment in the file describes how to use the macros)
- replaced std:: and boost::signals:: with SWIFTEN_SHRPTR_NAMESPACE:: and SWIFTEN_SIGNAL_NAMESPACE until the code compiled
- added some missing includes to boost

To conclude code changes, now STL shared pointers are used everywhere unless swift 2 or 3 is used. In such case boost shared pointers are used to interact with swift, but STL ones are used in code which is not interacting with swift. boost::signals were not replaced globally with boost::signals2, replacement was performed only in code which interact with swift and uses SWIFTEN_SIGNAL_NAMESPACE.

I am running latest version with XMPP frontend and libpurple backends with no issues. I also investigated why Travis CI  build is failing. It looks like it installs Swift 4 library which links to miniupnpc and natpmp. Those two are installed on the build server, but for some reason it is impossible to satisfy -lnatpmp and -lminiupnpc during compilation. I will further investigate this issue.

**Comment by vitalyster** [comment]
Travis was broken long time ago, since first commit after spectrum 2.0.3 release
See last successful build - https://travis-ci.org/hanzz/spectrum2/builds/112665507 - it was built again swiften 3.0, the next commit broke travis - https://travis-ci.org/hanzz/spectrum2/builds/113653485 - it uses the same libswiften-dev amd64 3.0-1, so I think problem is in spectrum code

**Comment by vitalyster** [comment]
And BTW, tests are passed on a real machine, and failing only in travis, so the problem may be in travis itself

**Comment by vladamatena** [comment]
For me two tests are failing on real machine:

- HTTPRequestTest::GETThreadPool
- UserRegistryTest::login

I have briefly looked into the problem and it seems not related to my changes. If I manage to fix those I will open separate pull request. Regarding this pull request I am done. Shall I do something more for this one?

**Comment by vitalyster** [comment]
`target_compile_features` is the cmake 3.1 feature, while we should be compatible with 2.8

**Comment by vladamatena** [comment]
Is it ok to require C++11 features?

**Comment by vitalyster** [comment]
In swift4 mode yes, otherwise no

**Comment by vladamatena** [comment]
I have hidden all STL shared pointers behind the SWIFTEN_SHRPTR_NAMESPACE, so that these are only used in Swift 4 mode. C++11 support is enabled based on detected Swift version without usage of target_compile_features.

**Pull request merged**
