### PR TITLE
General cleanup

### PR DESCRIPTION
**Pull request by Fank**
relates to #214

### CODE REVIEW

**Comment by Fank** [comment]
Dockerbuild were success.

**Comment by Fank** [comment]
@vitalyster read for merge

**Comment by vitalyster** [comment]
See https://github.com/hanzz/spectrum2/pull/214#issuecomment-307635959

**Comment by Fank** [comment]
I know See https://github.com/hanzz/spectrum2/pull/214#issuecomment-307637388 the `;` exists before sometimes. like https://github.com/hanzz/spectrum2/pull/216/files#diff-22513511fa76861fbcd8a1a579ee263fL68 current version of log4cxx compiles without problems.

**Comment by Fank** [comment]
with current i mean the fedora 23 version

**Comment by Fank** [comment]
@vitalyster still something open?

**Comment by vitalyster** [comment]
Please rebase on master to see test results

**Comment by Fank** [comment]
@vitalyster and finaly green ...

**Pull request merged**
