### PR TITLE
WIP: Alpine support

### PR DESCRIPTION
**Pull request by Fank**
Due a missing swiften prebuild is the alpine larget than the fedora image, so its compatible but does not make sence now.

All other changes are missing `;` or some preprocessor excludes.

### CODE REVIEW

**Comment by Fank** [comment]
@vitalyster this is read for merge

**Comment by vitalyster** [comment]
Can you please put clean up things in different patch?

**Comment by vitalyster** [comment]
```
missing ; or
```
LOG4CXX statements before latest changes doesn't require `;` and it may produce warning with older log4cxx

**Comment by Fank** [comment]
splitted and about the `;` stuff, it was sometimes there and sometimes not. i was not able to compile the code without `;` so i added it.

**Comment by Fank** [comment]
Waits for #216 so i can fix this one.

**Comment by vitalyster** [comment]
log4cxx was optional in some cases, please don't disable ENABLE_LOG

**Comment by Fank** [comment]
But it was commented out before?

**Comment by vitalyster** [comment]
Maybe it was configured in different way, I don't remember exactly

**Comment by Fank** [comment]
now it will use the existing config https://github.com/hanzz/spectrum2/blob/master/cmake_modules/log4cxxConfig.cmake which supports disabling

**Pull request closed without merging**
